MODEL:
  DEVICE: "cuda"
  META_ARCHITECTURE: "DQRF_DETR"
  WEIGHTS: "R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375] #[1.0, 1.0, 1.0] #std has been absorbed into its conv1 weights, so the std needs to be set 1. (for MSRA models, but we are using pytorch pretraining)
  BACKBONE:
    FREEZE_AT: 2 # FREEZE STEM + block 1
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "FrozenBN"
    OUT_FEATURES: ["res3", "res4", "res5"]

SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.0002
  STEPS: (197120,) # 118287 // 24 * 40
  GAMMA: 0.1
  MAX_ITER: 246400
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  SAMPLE_MULTIPLIER: 0.1
  CENTER_MULTPLIER: 0.1
  WEIGHT_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"

TEST:
  EVAL_PERIOD: 4928

DATALOADER:
  ASPECT_RATIO_GROUPING: True
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4

SEED: 42

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)

VERSION: 2